name: LAMP Deployment

on:
    workflow_dispatch:

jobs:
  linting:
    name: Lint Ansilbe files
    runs-on: ubuntu-latest

    steps:
    - name: checkout sources
      uses: actions/checkout@v2
    - name: Ansible Linting
      uses: ansible-community/ansible-lint-action@v6.2.1
      with:
        targets: |
          play1.yaml
          inventory.yaml

